In [1]:
pwd

'C:\\Users\\Asus\\31_DL_Code_Basics'

In [3]:
import os
os.chdir("D:\Research work\Thesis")

In [4]:
pwd

'D:\\Research work\\Thesis'

In [6]:
import numpy as np
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Kernel

In [7]:
import tensorflow

ModuleNotFoundError: No module named 'tensorflow'

In [8]:
import matplotlib.pyplot as plt


In [9]:
array_PolyC = np.loadtxt("numpy_Polycrys_TRAIN.csv", delimiter = ",", skiprows= 1)

In [10]:
array_PolyC

array([[ 5.        ,  5.        ,  4.18829152,  0.0445    ],
       [ 5.        , 14.        ,  4.32984401,  0.067     ],
       [ 5.        , 23.        ,  4.25515049,  0.06      ],
       [ 5.        , 32.        ,  4.68605247,  0.058     ],
       [ 8.        ,  8.        ,  4.2224182 ,  0.0495    ],
       [ 8.        , 17.        ,  4.46925789,  0.0535    ],
       [ 8.        , 26.        ,  4.60185109,  0.0585    ],
       [ 8.        , 35.        ,  4.60036369,  0.0645    ],
       [11.        , 11.        ,  4.14315876,  0.054     ],
       [11.        , 20.        ,  4.59959328,  0.058     ],
       [11.        , 29.        ,  4.62564011,  0.0515    ],
       [14.        ,  5.        ,  3.99273418,  0.047     ],
       [14.        , 14.        ,  4.19136892,  0.055     ],
       [14.        , 23.        ,  4.28483161,  0.047     ],
       [14.        , 32.        ,  4.9560783 ,  0.0575    ],
       [17.        ,  8.        ,  4.36541467,  0.061     ],
       [17.        , 17.

In [11]:
array_SingleC = np.loadtxt("numpy_SINGLEcrys.csv", delimiter = ",", skiprows= 1)

In [12]:
array_SingleC

array([[ 5.        ,  5.        , 14.3520355 ,  0.158     ],
       [ 5.        ,  8.        , 15.06016874,  0.159     ],
       [ 5.        , 11.        , 15.18654051,  0.1585    ],
       [ 5.        , 14.        , 14.93675485,  0.154     ],
       [ 5.        , 17.        , 15.01724489,  0.154     ],
       [ 5.        , 20.        , 15.61493541,  0.1595    ],
       [ 5.        , 23.        , 15.83782803,  0.158     ],
       [ 5.        , 26.        , 15.86482036,  0.1565    ],
       [ 5.        , 29.        , 16.02608281,  0.155     ],
       [ 5.        , 32.        , 16.34158891,  0.1555    ],
       [ 5.        , 35.        , 16.16485992,  0.152     ],
       [ 8.        ,  5.        , 16.15588857,  0.172     ],
       [ 8.        ,  8.        , 15.47610341,  0.1635    ],
       [ 8.        , 11.        , 15.87907845,  0.163     ],
       [ 8.        , 14.        , 15.84822315,  0.16      ],
       [ 8.        , 17.        , 16.43037905,  0.165     ],
       [ 8.        , 20.

In [13]:
array_PolyC.T

array([[ 5.        ,  5.        ,  5.        ,  5.        ,  8.        ,
         8.        ,  8.        ,  8.        , 11.        , 11.        ,
        11.        , 14.        , 14.        , 14.        , 14.        ,
        17.        , 17.        , 17.        , 17.        , 20.        ,
        20.        , 20.        , 23.        , 23.        , 23.        ,
        23.        , 26.        , 26.        , 26.        , 26.        ,
        29.        , 29.        , 29.        , 32.        , 32.        ,
        32.        , 32.        , 35.        , 35.        , 35.        ,
        35.        ],
       [ 5.        , 14.        , 23.        , 32.        ,  8.        ,
        17.        , 26.        , 35.        , 11.        , 20.        ,
        29.        ,  5.        , 14.        , 23.        , 32.        ,
         8.        , 17.        , 26.        , 35.        , 11.        ,
        20.        , 29.        ,  5.        , 14.        , 23.        ,
        32.        ,  8.     

In [14]:
# hf data  (PolyCrystal)
# all 1D array conversion
array_PolyC_Fe = array_PolyC.T[0]  # x_hf    x1_hf = Fe comp
array_PolyC_Ni = array_PolyC.T[1]  # x_hf    x2_hf = Ni comp

# Output y of Training data
array_PolyC_Tmax = array_PolyC.T[2]  #training data y_hf = Tmax PolyCrystal

In [15]:
array_PolyC_Fe.shape

(41,)

In [16]:
#MUlti-Feature x
# x = (Fe, Ni)

x_Poly_TRAIN = np.array( [array_PolyC_Fe, array_PolyC_Ni] )

In [17]:
x_Poly_TRAIN

array([[ 5.,  5.,  5.,  5.,  8.,  8.,  8.,  8., 11., 11., 11., 14., 14.,
        14., 14., 17., 17., 17., 17., 20., 20., 20., 23., 23., 23., 23.,
        26., 26., 26., 26., 29., 29., 29., 32., 32., 32., 32., 35., 35.,
        35., 35.],
       [ 5., 14., 23., 32.,  8., 17., 26., 35., 11., 20., 29.,  5., 14.,
        23., 32.,  8., 17., 26., 35., 11., 20., 29.,  5., 14., 23., 32.,
         8., 17., 26., 35., 11., 20., 29.,  5., 14., 23., 32.,  8., 17.,
        26., 35.]])

In [18]:
x_Poly_TRAIN = x_Poly_TRAIN.T

In [19]:
x_Poly_TRAIN

array([[ 5.,  5.],
       [ 5., 14.],
       [ 5., 23.],
       [ 5., 32.],
       [ 8.,  8.],
       [ 8., 17.],
       [ 8., 26.],
       [ 8., 35.],
       [11., 11.],
       [11., 20.],
       [11., 29.],
       [14.,  5.],
       [14., 14.],
       [14., 23.],
       [14., 32.],
       [17.,  8.],
       [17., 17.],
       [17., 26.],
       [17., 35.],
       [20., 11.],
       [20., 20.],
       [20., 29.],
       [23.,  5.],
       [23., 14.],
       [23., 23.],
       [23., 32.],
       [26.,  8.],
       [26., 17.],
       [26., 26.],
       [26., 35.],
       [29., 11.],
       [29., 20.],
       [29., 29.],
       [32.,  5.],
       [32., 14.],
       [32., 23.],
       [32., 32.],
       [35.,  8.],
       [35., 17.],
       [35., 26.],
       [35., 35.]])

In [20]:
x_Poly_TRAIN.shape

(41, 2)

In [21]:
#lf data  (SingleCrystal)
array_SingleC_Fe = array_SingleC.T[0]  # x_lf   x1_lf = Fe comp
array_SingleC_Ni = array_SingleC.T[1]  # x_lf   x2_lf = Ni comp

# Output y of Training Data
array_SingleC_Tmax = array_SingleC.T[2]  #training data y_lf = Tmax SingleCrystal

In [22]:
#combining x_lf = (x1_lf, x2_lf)
x_SingleC = np.array( [array_SingleC_Fe, array_SingleC_Ni] )
x_SingleC = x_SingleC.T

In [23]:
x_SingleC

array([[ 5.,  5.],
       [ 5.,  8.],
       [ 5., 11.],
       [ 5., 14.],
       [ 5., 17.],
       [ 5., 20.],
       [ 5., 23.],
       [ 5., 26.],
       [ 5., 29.],
       [ 5., 32.],
       [ 5., 35.],
       [ 8.,  5.],
       [ 8.,  8.],
       [ 8., 11.],
       [ 8., 14.],
       [ 8., 17.],
       [ 8., 20.],
       [ 8., 23.],
       [ 8., 26.],
       [ 8., 29.],
       [ 8., 32.],
       [ 8., 35.],
       [11.,  5.],
       [11.,  8.],
       [11., 11.],
       [11., 14.],
       [11., 17.],
       [11., 20.],
       [11., 23.],
       [11., 26.],
       [11., 29.],
       [11., 32.],
       [11., 35.],
       [14.,  5.],
       [14.,  8.],
       [14., 11.],
       [14., 14.],
       [14., 17.],
       [14., 20.],
       [14., 23.],
       [14., 26.],
       [14., 29.],
       [14., 32.],
       [14., 35.],
       [17.,  5.],
       [17.,  8.],
       [17., 11.],
       [17., 14.],
       [17., 17.],
       [17., 20.],
       [17., 23.],
       [17., 26.],
       [17.,

In [24]:
x_SingleC.shape

(121, 2)

In [25]:
#low-fidelity training data - (Fe,Ni)

#MUST be reshaped as tensor (2xn matrix) to feed to tensorflow
x_lf = x_SingleC        # x = (x1, x2) = (Fe, Ni) comp  2 dim input, shape(41, 2)
y_lf = array_SingleC_Tmax.reshape((-1,1))        # y = Tmax,  must be reshaped to  ( , 1) for Tensorflow

#high-fidelity training data
x_hf = x_Poly_TRAIN            # (Fe, Ni) for Poly Crystal
y_hf = array_PolyC_Tmax.reshape((-1, 1))          # y = Tmax PolyCrystal. must be reshaped to ( , 1) for Tensorflow

In [26]:
Xmin = x_lf.min(0)
Xmax = x_lf.max(0)
Ymin = y_lf.min(0)
Ymax = y_lf.max(0)

In [27]:
Xhmin = np.hstack((Xmin, Ymin))
Xhmax = np.hstack((Xmax, Ymax))